### ISSUE TITLE
Unable to run on CentOS 6.6

### ISSUE THREAD

**Issue by jacek99** [onddo/swap_tuning-cookbook#2]
Got this error while running on CentOS 6.6:

         ArgumentError
         -------------
         swap_file[/swapfile0] (swap_tuning::default line 42) had an error: ArgumentError: Cannot find a provider for swap_file[/swapfile0] on centos version 6.6
         
         Cookbook Trace:
         ---------------
           /tmp/kitchen/cache/cookbooks/swap_tuning/recipes/default.rb:45:in `from_file'
           /tmp/kitchen/cache/cookbooks/gso-build/recipes/oracle_xe.rb:12:in `from_file'
           /tmp/kitchen/cache/cookbooks/gso-build/recipes/jenkins_master.rb:24:in `from_file'

Code:

     # Oracle XE requires 2GB of swap space
    node.default['swap_tuning']['size'] = 2048
    include_recipe 'swap_tuning'

**Comment by jacek99** [comment]
I was running this as part of a recipe in Test Kitchen, made sure to clean the VM and try from scratch multiple times, always the same error

**Comment by jacek99** [comment]
it is bizarre because now it also happens on centos 7:

     swap_file[/swapfile0] (swap_tuning::default line 42) had an error: ArgumentError: Cannot find a provider for swap_file[/swapfile0] on centos version 7.0.1406

**Comment by zuazo** [comment]
This seems to be caused by a Chef `12.4.0` bug. See here: https://github.com/sethvargo-cookbooks/swap/issues/22

**Comment by zuazo** [comment]
Hello @jacek99,

A fix for this has been merged in the Chef master branch: https://github.com/chef/chef/pull/3586

**Comment by jpmurray** [comment]
Just adding my voice to say that it occurs with Ubuntu 14.04 also. I guess in the meantime the next version of Chef comes up, there is nothing we can do ?

**Comment by zuazo** [comment]
@jpmurray a fix is described here: https://github.com/sethvargo-cookbooks/swap/issues/22#issuecomment-115048224

But AFAIK this needs to be fixed inside the swap cookbook.

**Comment by zuazo** [comment]
The fix/patch for the `swap` cookbook has been merged in master: https://github.com/sethvargo-cookbooks/swap/pull/24

**Comment by jpmurray** [comment]
@zuazo thanks for the notification!

**Comment by zuazo** [comment]
The latest Chef release, [`12.4.1`](https://github.com/chef/chef/blob/master/CHANGELOG.md#1241), should have fixed this problem forever.
